/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacman_demo_v2;

/**
 *
 * @author luuhu
 */
public class StartMenu_Frame extends javax.swing.JFrame {

    /**
     * Creates new form StartMenu_Frame
     */
    public StartMenu_Frame() {
        initComponents();
        
        this.setSize(694, 750);          // Đặt kích thước
        this.setResizable(false);        // Không cho phép thay đổi kích thước
        this.setLocationRelativeTo(null); // Đặt cửa sổ ra giữa màn hình
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbPlay = new javax.swing.JLabel();
        lbTutorial = new javax.swing.JLabel();
        lbPlayRankingBoard = new javax.swing.JLabel();
        lbAboutUs = new javax.swing.JLabel();
        lbExit = new javax.swing.JLabel();
        lbbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        lbPlay.setBackground(new java.awt.Color(0, 0, 255));
        lbPlay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPlay.setForeground(new java.awt.Color(255, 255, 0));
        lbPlay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/playIcon.png"))); // NOI18N
        lbPlay.setText("PLAY");
        lbPlay.setOpaque(true);
        jPanel1.add(lbPlay);
        lbPlay.setBounds(10, 380, 670, 50);

        lbTutorial.setBackground(new java.awt.Color(0, 0, 255));
        lbTutorial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTutorial.setForeground(new java.awt.Color(255, 255, 0));
        lbTutorial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTutorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tutorialIcon.png"))); // NOI18N
        lbTutorial.setText("HOW TO PLAY");
        lbTutorial.setOpaque(true);
        jPanel1.add(lbTutorial);
        lbTutorial.setBounds(10, 440, 670, 50);

        lbPlayRankingBoard.setBackground(new java.awt.Color(0, 0, 255));
        lbPlayRankingBoard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPlayRankingBoard.setForeground(new java.awt.Color(255, 255, 0));
        lbPlayRankingBoard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPlayRankingBoard.setText("RANKING BOARD");
        lbPlayRankingBoard.setOpaque(true);
        jPanel1.add(lbPlayRankingBoard);
        lbPlayRankingBoard.setBounds(10, 500, 670, 50);

        lbAboutUs.setBackground(new java.awt.Color(0, 0, 255));
        lbAboutUs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAboutUs.setForeground(new java.awt.Color(255, 255, 0));
        lbAboutUs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAboutUs.setText("ABOUT US");
        lbAboutUs.setOpaque(true);
        jPanel1.add(lbAboutUs);
        lbAboutUs.setBounds(10, 560, 670, 50);

        lbExit.setBackground(new java.awt.Color(0, 0, 255));
        lbExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbExit.setForeground(new java.awt.Color(255, 255, 0));
        lbExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbExit.setText("EXIT");
        lbExit.setOpaque(true);
        jPanel1.add(lbExit);
        lbExit.setBounds(10, 620, 670, 50);

        lbbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PacMan loop.gif"))); // NOI18N
        lbbackground.setOpaque(true);
        jPanel1.add(lbbackground);
        lbbackground.setBounds(0, 0, 690, 750);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartMenu_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartMenu_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartMenu_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartMenu_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartMenu_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAboutUs;
    private javax.swing.JLabel lbExit;
    private javax.swing.JLabel lbPlay;
    private javax.swing.JLabel lbPlayRankingBoard;
    private javax.swing.JLabel lbTutorial;
    private javax.swing.JLabel lbbackground;
    // End of variables declaration//GEN-END:variables
}
