/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacman_demo_v2;

/**
 *
 * @author luuhu
 */
public class ChoiceCharacter_Frame extends javax.swing.JFrame {

    public int choice;
    private GlassPane glassPane;
    
    /**
     * Creates new form StartMenu_Frame
     */
    public ChoiceCharacter_Frame() {
        initComponents();
        
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"));
        this.setIconImage(icon.getImage());
        
        this.setSize(694, 725);          // Đặt kích thước
        this.setResizable(false);        // Không cho phép thay đổi kích thước
        this.setLocationRelativeTo(null); // Đặt cửa sổ ra giữa màn hình
        
        
        glassPane = new GlassPane(this);
        setGlassPane(glassPane);
        glassPane.setVisible(true);
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbWoMan = new javax.swing.JLabel();
        lbMan = new javax.swing.JLabel();
        lbLogo = new javax.swing.JLabel();
        lbChoiceMan = new javax.swing.JLabel();
        lbChoiceWoMan = new javax.swing.JLabel();
        lbbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");

        jPanel1.setLayout(null);

        lbWoMan.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbWoMan.setText("WOMAN");
        lbWoMan.setOpaque(true);
        jPanel1.add(lbWoMan);
        lbWoMan.setBounds(490, 440, 160, 90);

        lbMan.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbMan.setText("Man");
        lbMan.setOpaque(true);
        jPanel1.add(lbMan);
        lbMan.setBounds(130, 440, 100, 90);

        lbLogo.setBackground(new java.awt.Color(204, 255, 0));
        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pacManLogo.png"))); // NOI18N
        lbLogo.setOpaque(true);
        jPanel1.add(lbLogo);
        lbLogo.setBounds(270, 120, 190, 190);

        lbChoiceMan.setBackground(new java.awt.Color(0, 255, 255));
        lbChoiceMan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbChoiceMan.setForeground(new java.awt.Color(204, 204, 0));
        lbChoiceMan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbChoiceMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/playIcon.png"))); // NOI18N
        lbChoiceMan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbChoiceMan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbChoiceManMouseClicked(evt);
            }
        });
        jPanel1.add(lbChoiceMan);
        lbChoiceMan.setBounds(-80, 550, 540, 50);

        lbChoiceWoMan.setBackground(new java.awt.Color(0, 255, 255));
        lbChoiceWoMan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbChoiceWoMan.setForeground(new java.awt.Color(255, 0, 0));
        lbChoiceWoMan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbChoiceWoMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exitIcon.png"))); // NOI18N
        lbChoiceWoMan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbChoiceWoMan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbChoiceWoManMouseClicked(evt);
            }
        });
        jPanel1.add(lbChoiceWoMan);
        lbChoiceWoMan.setBounds(270, 550, 540, 50);

        lbbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PacManloop.gif"))); // NOI18N
        lbbackground.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lbbackground);
        lbbackground.setBounds(0, 10, 726, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbChoiceManMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbChoiceManMouseClicked
        // TODO add your handling code here:
        PacManMainGame_Frame pacManGame = new PacManMainGame_Frame();
        choice = 1;
        pacManGame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lbChoiceManMouseClicked

    private void lbChoiceWoManMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbChoiceWoManMouseClicked
        // TODO add your handling code here:
        PacManMainGame_Frame pacManGame = new PacManMainGame_Frame();
        choice = 2;
        pacManGame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lbChoiceWoManMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoiceCharacter_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoiceCharacter_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoiceCharacter_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoiceCharacter_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChoiceCharacter_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbChoiceMan;
    private javax.swing.JLabel lbChoiceWoMan;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbMan;
    private javax.swing.JLabel lbWoMan;
    private javax.swing.JLabel lbbackground;
    // End of variables declaration//GEN-END:variables
}
