/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacman_demo_v2;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author luuhu
 */
public class GameOver_Frame extends javax.swing.JDialog {

    private int userChoice = JOptionPane.CLOSED_OPTION;
    private long finalScore;
    private String finalTime;
    private ScoreManager scoreManager;
    
    /**
     * Creates new form CustomDialog
     */
    public GameOver_Frame(java.awt.Frame parent, boolean modal, long finalScore, String finalTime) {
        super(parent, modal);
        
        this.finalScore = finalScore;
        this.finalTime = finalTime;
        this.scoreManager = new ScoreManager();
        
        setUndecorated(true);
        setBackground(new Color(0, 0, 0, 0));
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"));
        this.setIconImage(icon.getImage());
        
        initComponents();
        
        // Cập nhật text cho các label điểm và thời gian sau khi initComponents()
        lbScore.setText("" + this.finalScore);
        lbTime.setText(this.finalTime);
        
        txtName.setOpaque(false);
        txtName.setBackground(new Color(0, 0, 0, 0)); // Vẫn nên dùng cách 1
        txtName.setBorder(null); // Tắt hoàn toàn đường viền

        setSize(400, 492);
        setLocationRelativeTo(parent);
    }

    public int showDialog() {
        this.setVisible(true);
        return this.userChoice;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JTextField();
        lbName = new javax.swing.JLabel();
        btnNo = new javax.swing.JButton();
        btnYes = new javax.swing.JButton();
        lbScore = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setUndecorated(true);
        getContentPane().setLayout(null);

        txtName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(153, 255, 255));
        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName.setOpaque(false);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(90, 390, 220, 30);

        lbName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/NameLB.png"))); // NOI18N
        getContentPane().add(lbName);
        lbName.setBounds(80, 380, 240, 50);

        btnNo.setBackground(new java.awt.Color(255, 51, 51));
        btnNo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnNo.setForeground(new java.awt.Color(255, 255, 255));
        btnNo.setText("CANCEL");
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNo);
        btnNo.setBounds(100, 435, 80, 40);

        btnYes.setBackground(new java.awt.Color(0, 204, 0));
        btnYes.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnYes.setForeground(new java.awt.Color(255, 255, 255));
        btnYes.setText("OK");
        btnYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesActionPerformed(evt);
            }
        });
        getContentPane().add(btnYes);
        btnYes.setBounds(220, 435, 80, 40);

        lbScore.setBackground(new java.awt.Color(204, 255, 255));
        lbScore.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbScore.setForeground(new java.awt.Color(255, 153, 255));
        lbScore.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbScore.setText("1111");
        getContentPane().add(lbScore);
        lbScore.setBounds(90, 65, 100, 20);

        lbTime.setBackground(new java.awt.Color(255, 255, 255));
        lbTime.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbTime.setForeground(new java.awt.Color(255, 153, 153));
        lbTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTime.setText("1111");
        getContentPane().add(lbTime);
        lbTime.setBounds(220, 65, 120, 20);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gameOverIcon.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 493);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesActionPerformed
        // TODO add your handling code here:
        String username = txtName.getText().trim();
        
        // Kiểm tra tên hợp lệ
        // File scores.txt của bạn dùng khoảng trắng để phân tách
        // nên tên người dùng không được chứa khoảng trắng.
        if (username.isEmpty() || username.contains(" ")) {
            JOptionPane.showMessageDialog(this, 
                    "Invalid name. Please enter the name without spaces.", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            return; // Không đóng dialog
        }
        // Tên người dùng không được chứa quá 11 ký tự
        if (username.length() > 11) {
            JOptionPane.showMessageDialog(this, 
                    "Invalid name. The name has a maximum length of 11 characters.", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            return; // Không đóng dialog
        }
        
        // Lưu điểm
        scoreManager.addScore(username, finalScore, finalTime);
        
        this.userChoice = JOptionPane.YES_OPTION;
        this.dispose(); // Đóng dialog
    }//GEN-LAST:event_btnYesActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        // TODO add your handling code here:
        this.userChoice = JOptionPane.YES_OPTION;
        this.dispose(); // Đóng dialog
        StartMenu_Frame sm = new StartMenu_Frame();
        sm.setVisible(true);
    }//GEN-LAST:event_btnNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameOver_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameOver_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameOver_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameOver_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GameOver_Frame dialog = new GameOver_Frame(new javax.swing.JFrame(), true, 12345, "00:01:30");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnYes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbScore;
    private javax.swing.JLabel lbTime;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
