/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacman_demo_v2;

import javax.swing.JOptionPane;


/**
 *
 * @author luuhu
 */
public class PacManMainGame_Frame extends javax.swing.JFrame {
    
    public void pacmanHit() {
        
        int lives = ((BoardPanel) pnlBoard).totalLives;
        lives--;
        ((BoardPanel) pnlBoard).totalLives = lives; // Giảm số mạng đi 1
        lbCountLive.setText(String.valueOf(lives)); // Cập nhật text trên label

        if (lives <= 0) {
            // Tạm dừng game timer trong khi hộp thoại hiển thị
            ((BoardPanel) pnlBoard).stopTimers();

            String[] options = {"Replay", "Exit"};
            int choice = JOptionPane.showOptionDialog(
                this,                          // Parent component
                "Game Over! Do you want to play again?", // Message
                "Game Over",                   // Title
                JOptionPane.DEFAULT_OPTION,    // Option type
                JOptionPane.QUESTION_MESSAGE,  // Message type
                null,                          // Icon
                options,                       // Custom button texts
                options[0]                     // Default button
            );

            if (choice == 0) {
                // Người dùng chọn "Replay"
                ((BoardPanel) pnlBoard).replayGame();
                lbCountLive.setText("3");
            } else {
                // Người dùng chọn "Exit" hoặc đóng hộp thoại
                System.exit(0);
            }
        } else {
            // Nếu còn mạng, chỉ reset vị trí Pac-Man
            ((BoardPanel) pnlBoard).resetPosition();
            // Tạm dừng 500ms
            ((BoardPanel) pnlBoard).stopTimers();
            try {
                Thread.sleep(500);
            } catch (InterruptedException e) {
                // Lỗi này xảy ra nếu có một luồng khác ngắt quãng luồng này.
                // Trong game đơn giản, bạn có thể bỏ qua hoặc in ra lỗi.
                e.printStackTrace();
            }
            ((BoardPanel) pnlBoard).startTimers();
                    
        }
    }
    
    /**
     * Creates new form PacMan_Demo_v11
     */
    public PacManMainGame_Frame() {
        initComponents();


        // Khóa khích thước cửa sổ game
        this.setResizable(false);
        
        
        pnlBoard.requestFocusInWindow(); 
        
        this.setResizable(false);
        this.setTitle("PacMan Demo"); // Thêm tiêu đề cho cửa sổ
        this.setLocationRelativeTo(null); // Hiển thị cửa sổ ở giữa màn hình
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtfLive1 = new javax.swing.JTextField();
        pnBoard = new javax.swing.JPanel();
        pnlTile = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        lbCountLive = new javax.swing.JLabel();
        lbCountTime = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();
        lbLive = new javax.swing.JLabel();
        lbScore = new javax.swing.JLabel();
        lbCountScore = new javax.swing.JLabel();
        pnlBoard = new BoardPanel(this);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        txtfLive1.setText("LIVE:");
        txtfLive1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfLive1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setSize(new java.awt.Dimension(608, 672));

        pnBoard.setBackground(new java.awt.Color(0, 0, 0));
        pnBoard.setName("PacMan"); // NOI18N

        pnlTile.setBackground(new java.awt.Color(0, 153, 255));
        pnlTile.setBorder(javax.swing.BorderFactory.createTitledBorder("PacMan Game"));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pacmanlogo.jpg"))); // NOI18N

        btnHome.setBackground(new java.awt.Color(255, 0, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/homeIcon.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        lbCountLive.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbCountLive.setForeground(new java.awt.Color(255, 255, 0));
        lbCountLive.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCountLive.setText("3");

        lbCountTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCountTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCountTime.setText("00:00:00");

        lbTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/timeIcon.png"))); // NOI18N
        lbTime.setText("TIME");

        lbLive.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbLive.setForeground(new java.awt.Color(51, 255, 102));
        lbLive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pacman/pacnu1phai.png"))); // NOI18N
        lbLive.setText("LIVE");

        lbScore.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbScore.setForeground(new java.awt.Color(255, 255, 255));
        lbScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/scoreIcon.png"))); // NOI18N
        lbScore.setText("SCORE");

        lbCountScore.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbCountScore.setForeground(new java.awt.Color(255, 255, 255));
        lbCountScore.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCountScore.setText("0");

        javax.swing.GroupLayout pnlTileLayout = new javax.swing.GroupLayout(pnlTile);
        pnlTile.setLayout(pnlTileLayout);
        pnlTileLayout.setHorizontalGroup(
            pnlTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTileLayout.createSequentialGroup()
                .addGroup(pnlTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTileLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbScore)
                            .addComponent(lbTime)
                            .addComponent(lbLive))
                        .addGap(19, 19, 19)
                        .addGroup(pnlTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbCountLive, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCountTime)
                            .addComponent(lbCountScore, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnHome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        pnlTileLayout.setVerticalGroup(
            pnlTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTileLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCountTime, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTime))
                .addGap(26, 26, 26)
                .addGroup(pnlTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLive)
                    .addComponent(lbCountLive))
                .addGap(26, 26, 26)
                .addGroup(pnlTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbScore)
                    .addComponent(lbCountScore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlTileLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBoardLayout = new javax.swing.GroupLayout(pnlBoard);
        pnlBoard.setLayout(pnlBoardLayout);
        pnlBoardLayout.setHorizontalGroup(
            pnlBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlBoardLayout.setVerticalGroup(
            pnlBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnBoardLayout = new javax.swing.GroupLayout(pnBoard);
        pnBoard.setLayout(pnBoardLayout);
        pnBoardLayout.setHorizontalGroup(
            pnBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBoardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnBoardLayout.setVerticalGroup(
            pnBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBoardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        // Tạm dừng game
        ((BoardPanel) pnlBoard).stopTimers();

        // Hiển thị hộp thoại xác nhận
        int choice = JOptionPane.showConfirmDialog(
            this, // parent component
            "Do you want to return to the main menu?\nYour current game progress will be lost.", // message
            "Return to Main Menu", // title
            JOptionPane.YES_NO_OPTION, // option type
            JOptionPane.QUESTION_MESSAGE // message type
        );

        // Xử lý lựa chọn
        if (choice == JOptionPane.YES_OPTION) {
            // Nếu người dùng chọn "Yes"
            StartMenu_Frame startMenu = new StartMenu_Frame();
            startMenu.setVisible(true); // Mở lại menu chính
            this.dispose(); // Đóng cửa sổ game hiện tại
        } else {
            // Nếu người dùng chọn "No" hoặc đóng hộp thoại
            // Tiếp tục game (bạn sẽ cần tạo phương thức này trong BoardPanel)
            ((BoardPanel) pnlBoard).startTimers();
            pnlBoard.requestFocusInWindow(); // Trả lại focus cho panel game để bắt sự kiện phím
        }
    }//GEN-LAST:event_btnHomeActionPerformed

    private void txtfLive1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfLive1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfLive1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PacManMainGame_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PacManMainGame_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PacManMainGame_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PacManMainGame_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PacManMainGame_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public javax.swing.JLabel lbCountLive;
    public javax.swing.JLabel lbCountScore;
    public javax.swing.JLabel lbCountTime;
    private javax.swing.JLabel lbLive;
    private javax.swing.JLabel lbScore;
    private javax.swing.JLabel lbTime;
    private javax.swing.JPanel pnBoard;
    private javax.swing.JPanel pnlBoard;
    private javax.swing.JPanel pnlTile;
    private javax.swing.JTextField txtfLive1;
    // End of variables declaration//GEN-END:variables
}