/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacman_demo_v2;

import javax.swing.JOptionPane;

/**
 *
 * @author luuhu
 */
public class PacManMainGame_Frame extends javax.swing.JFrame {
    private int choice;
    // Khởi tạo 1 màn làm mở cửa sổ
    private GlassPane glassPane;

    public int getChoice() {
        return choice;
    }
    
    public void uploadLives() {
        lbCountLive.setText(String.valueOf(((BoardPanel) pnlBoard).totalLives)); // Cập nhật text trên label
    }
    
    public void pacmanHit() {
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"));
        this.setIconImage(icon.getImage());
        int lives = ((BoardPanel) pnlBoard).totalLives;
        lives--;
        
        ((BoardPanel) pnlBoard).totalLives = lives; // Giảm số mạng đi 1
        uploadLives();

        // Game over
        if (lives <= 0) {
            // Tạm dừng game
            ((BoardPanel) pnlBoard).stopTimers();
            
            // Lấy điểm số và thời gian cuối cùng từ các JLabel
            long finalScore = 0;
            try {
                finalScore = Long.parseLong(lbCountScore.getText());
            } catch (NumberFormatException e) {
                e.printStackTrace();
            }

            String finalTime = lbCountTime.getText();
            
            // Làm mờ nền game
            glassPane.setVisible(true);

            // Tạo và hiển thị hộp thoại tùy chỉnh
            GameOver_Frame gameOverDialog = new GameOver_Frame(this, true, finalScore, finalTime);
            gameOverDialog.showDialog();

            // Tắt lớp làm mờ
            glassPane.setVisible(false);

            StartMenu_Frame startMenu = new StartMenu_Frame();
            startMenu.setVisible(true); // Mở lại menu chính
            this.dispose(); // Đóng cửa sổ hiện tại
                      
        } else {
            // Nếu còn mạng, chỉ reset vị trí Pac-Man
            ((BoardPanel) pnlBoard).resetPosition();
            // Tạm dừng 500ms
            ((BoardPanel) pnlBoard).stopTimers();
            try {
                Thread.sleep(500);
            } catch (InterruptedException e) {
                // Lỗi này xảy ra nếu có một luồng khác ngắt quãng luồng này.
                // Trong game đơn giản, bạn có thể bỏ qua hoặc in ra lỗi.
                e.printStackTrace();
            }
            ((BoardPanel) pnlBoard).startTimers();

        }
    }
    
    /**
     * Cập nhật thanh tiến trình VÀ icon Red Bull.
     * @param isActive true nếu Red Bull đang kích hoạt
     * @param remainingTicks Số "ticks" (50ms) còn lại (từ 200 -> 0)
     */
    public void updateRedBullTimer(boolean isActive, int remainingTicks) {
        prbarRedBull.setVisible(isActive);
        lbRedBullIcon.setVisible(isActive);

        if (isActive) {
            // Chuyển đổi ticks (0-200) sang giây (0.0 - 10.0)
            // 20 ticks = 1 giây
            double secondsLeft = (double) remainingTicks / 20.0; 
            
            prbarRedBull.setValue(remainingTicks);
            // Định dạng chuỗi để hiển thị 1 chữ số thập phân (ví dụ: "9.8s")
            prbarRedBull.setString(String.format("Red Bull: %.1fs", secondsLeft));
        } else {
            prbarRedBull.setValue(0);
            prbarRedBull.setString("Red Bull: Inactive");
        }
    }

    
    /**
     * Creates new form PacMan_Demo_v11
     */
    public PacManMainGame_Frame(int choice) {
        this.choice = choice;
        System.out.println("choice: " + choice);
        initComponents();
        
        prbarRedBull.setVisible(false);
        lbRedBullIcon.setVisible(false);
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"));
        this.setIconImage(icon.getImage());

        // Khóa khích thước cửa sổ game
        this.setResizable(false);

        pnlBoard.requestFocusInWindow();

        this.setResizable(false);
        this.setTitle("PacMan Game"); // Thêm tiêu đề cho cửa sổ
        this.setLocationRelativeTo(null); // Hiển thị cửa sổ ở giữa màn hình

        glassPane = new GlassPane(this);
        setGlassPane(glassPane);
        
        lbCountLive.setText(((BoardPanel) pnlBoard).totalLives + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtfLive1 = new javax.swing.JTextField();
        pnBoard = new javax.swing.JPanel();
        pnlTile = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbCountLive = new javax.swing.JLabel();
        lbCountTime = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();
        lbLive = new javax.swing.JLabel();
        lbScore = new javax.swing.JLabel();
        lbCountScore = new javax.swing.JLabel();
        lbHome = new javax.swing.JLabel();
        prbarRedBull = new javax.swing.JProgressBar();
        lbRedBullIcon = new javax.swing.JLabel();
        pnlBoard = new BoardPanel(this);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        txtfLive1.setText("LIVE:");
        txtfLive1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfLive1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setSize(new java.awt.Dimension(608, 672));

        pnBoard.setBackground(new java.awt.Color(0, 0, 0));
        pnBoard.setName("PacMan"); // NOI18N

        pnlTile.setBackground(new java.awt.Color(153, 204, 255));
        pnlTile.setBorder(javax.swing.BorderFactory.createTitledBorder("PacMan Game"));
        pnlTile.setForeground(new java.awt.Color(255, 255, 255));
        pnlTile.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PacmanGameplayLogo.png"))); // NOI18N

        lbCountLive.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbCountLive.setForeground(new java.awt.Color(255, 255, 0));
        lbCountLive.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lbCountTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbCountTime.setForeground(new java.awt.Color(255, 255, 255));
        lbCountTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCountTime.setText("00:00:00");

        lbTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/timeIcon.png"))); // NOI18N
        lbTime.setText("TIME");

        lbLive.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbLive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pacman/pacnu1phai.png"))); // NOI18N
        lbLive.setText("LIVE");

        lbScore.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/scoreIcon.png"))); // NOI18N
        lbScore.setText("SCORE");

        lbCountScore.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbCountScore.setForeground(new java.awt.Color(255, 255, 255));
        lbCountScore.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCountScore.setText("0");

        lbHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home.png"))); // NOI18N
        lbHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbHomeMouseClicked(evt);
            }
        });
        lbHome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbHomeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lbHomeKeyTyped(evt);
            }
        });

        prbarRedBull.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prbarRedBull.setForeground(new java.awt.Color(102, 102, 102));
        prbarRedBull.setMaximum(200);
        prbarRedBull.setToolTipText("");
        prbarRedBull.setOpaque(true);
        prbarRedBull.setString("Red Bull: Inactive");
        prbarRedBull.setStringPainted(true);

        lbRedBullIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/item/redBull.png"))); // NOI18N

        javax.swing.GroupLayout pnlTileLayout = new javax.swing.GroupLayout(pnlTile);
        pnlTile.setLayout(pnlTileLayout);
        pnlTileLayout.setHorizontalGroup(
            pnlTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTileLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTileLayout.createSequentialGroup()
                        .addComponent(lbTime)
                        .addGap(18, 18, 18)
                        .addComponent(lbCountTime, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTileLayout.createSequentialGroup()
                        .addComponent(lbLive)
                        .addGap(21, 21, 21)
                        .addComponent(lbCountLive, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTileLayout.createSequentialGroup()
                        .addComponent(lbScore)
                        .addGap(6, 6, 6)
                        .addComponent(lbCountScore, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbHome, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTileLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTileLayout.createSequentialGroup()
                        .addComponent(lbRedBullIcon)
                        .addGap(4, 4, 4)
                        .addComponent(prbarRedBull, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnlTileLayout.setVerticalGroup(
            pnlTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTileLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTime)
                    .addComponent(lbCountTime))
                .addGap(26, 26, 26)
                .addGroup(pnlTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLive)
                    .addComponent(lbCountLive))
                .addGap(26, 26, 26)
                .addGroup(pnlTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbScore)
                    .addComponent(lbCountScore))
                .addGap(11, 11, 11)
                .addComponent(lbHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlTileLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(pnlTileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRedBullIcon)
                    .addGroup(pnlTileLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(prbarRedBull, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pnlBoard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout pnlBoardLayout = new javax.swing.GroupLayout(pnlBoard);
        pnlBoard.setLayout(pnlBoardLayout);
        pnlBoardLayout.setHorizontalGroup(
            pnlBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlBoardLayout.setVerticalGroup(
            pnlBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnBoardLayout = new javax.swing.GroupLayout(pnBoard);
        pnBoard.setLayout(pnBoardLayout);
        pnBoardLayout.setHorizontalGroup(
            pnBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBoardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlTile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnBoardLayout.setVerticalGroup(
            pnBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBoardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfLive1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfLive1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfLive1ActionPerformed

    private void lbHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbHomeMouseClicked
        // TODO add your handling code here:
        // Tạm dừng game
        ((BoardPanel) pnlBoard).stopTimers(); // Dòng này của bạn

        // 1. Làm mờ nền game
        glassPane.setVisible(true);

        // 2. Tạo và hiển thị hộp thoại tùy chỉnh
        CustomDialog dialog = new CustomDialog(this, true);
        int choice = dialog.showDialog();

        // 3. Tắt lớp làm mờ
        glassPane.setVisible(false);

        // 4. Xử lý lựa chọn
        if (choice == JOptionPane.YES_OPTION) {
            // Nếu người dùng chọn "Yes"
            StartMenu_Frame startMenu = new StartMenu_Frame();
            startMenu.setVisible(true); // Mở lại menu chính
            this.dispose(); // Đóng cửa sổ game hiện tại
            System.out.println("Returning to main menu..."); // In ra để kiểm tra
        } else {
            // Nếu người dùng chọn "No"
            // Tiếp tục game
            ((BoardPanel) pnlBoard).startTimers();
            pnlBoard.requestFocusInWindow(); // Trả lại focus
            System.out.println("Resuming game..."); // In ra để kiểm tra
        }
    }//GEN-LAST:event_lbHomeMouseClicked

    private void lbHomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbHomeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_lbHomeKeyTyped

    private void lbHomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbHomeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbHomeKeyPressed

    /**
     * @param args the command line arguments
     */
    

    public static void main(String args[]) {
         //final int choice = choice; 
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PacManMainGame_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PacManMainGame_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PacManMainGame_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PacManMainGame_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        //static int x = this.choice;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PacManMainGame_Frame(0).setVisible(true);
            }
        }); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public javax.swing.JLabel lbCountLive;
    public javax.swing.JLabel lbCountScore;
    public javax.swing.JLabel lbCountTime;
    private javax.swing.JLabel lbHome;
    private javax.swing.JLabel lbLive;
    private javax.swing.JLabel lbRedBullIcon;
    private javax.swing.JLabel lbScore;
    private javax.swing.JLabel lbTime;
    private javax.swing.JPanel pnBoard;
    private javax.swing.JPanel pnlBoard;
    private javax.swing.JPanel pnlTile;
    private javax.swing.JProgressBar prbarRedBull;
    private javax.swing.JTextField txtfLive1;
    // End of variables declaration//GEN-END:variables
}
