/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacman_demo_v2;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author luuhu
 */
public class RankingBoard_Frame extends javax.swing.JFrame {

    private ScoreManager scoreManager;
    
    /**
     * Creates new form StartMenu_Frame
     */
    public RankingBoard_Frame() {
        initComponents();
        
        this.setSize(694, 725);          // Đặt kích thước
        this.setResizable(false);        // Không cho phép thay đổi kích thước
        this.setLocationRelativeTo(null); // Đặt cửa sổ ra giữa màn hình
        
        scoreManager = new ScoreManager();
        styleTable(); // Gọi styleTable trước để định dạng bảng
        loadDataToTable(); // Tải và hiển thị điểm
    }
    
    /**
     * Phương thức này đã được sửa để đọc trực tiếp từ file Scores.txt
     */
    private void loadDataToTable() {
        DefaultTableModel model = (DefaultTableModel) tbRankingBoard.getModel();
        model.setRowCount(0); // Xóa hết dữ liệu cũ trên bảng

        // Tên file phải khớp với tên file được ghi bởi ScoreManager
        File scoreFile = new File("scores.txt"); 

        if (!scoreFile.exists()) {
            System.out.println("File Scores.txt does not exist. The leaderboard will be empty.");
            return; // Dừng lại nếu không tìm thấy file
        }

        try (Scanner sc = new Scanner(scoreFile)) {
            while (sc.hasNextLine()) {
                String line = sc.nextLine().trim();
                if (!line.isEmpty()) {
                    // Định dạng file mong muốn: "Rank Name Time Score"
                    // Ví dụ: "1 LuuHuynh 00:00:45 1200"
                    String[] parts = line.split("\\s+", 4); // Tách dòng thành 4 phần
                    
                    if (parts.length == 4) {
                        // Thêm dữ liệu vào bảng theo đúng thứ tự các cột
                        model.addRow(new Object[]{parts[0], parts[1], parts[2], parts[3]});
                    }
                }
            }
        } catch (FileNotFoundException e) {
            System.err.println("Đã xảy ra lỗi khi đọc file: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    /**
     * Tùy chỉnh giao diện cho JTable
     */
    private void styleTable() {
        // Căn giữa nội dung trong các ô
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        
        tbRankingBoard.setDefaultRenderer(Object.class, centerRenderer);

        // Tùy chỉnh Header
        JTableHeader header = tbRankingBoard.getTableHeader();
        header.setFont(new Font("Tahoma", Font.BOLD, 16));
        header.setBackground(new Color(255, 165, 0));
        header.setForeground(Color.BLACK);
        header.setPreferredSize(new Dimension(100, 40));
        header.setReorderingAllowed(false); // Không cho kéo thả cột

        // Tùy chỉnh các dòng
        tbRankingBoard.setRowHeight(30);
        tbRankingBoard.setFont(new Font("Tahoma", Font.PLAIN, 14));
        tbRankingBoard.setSelectionBackground(new Color(255, 228, 181));
        
        // Tùy chỉnh kích thước cột
        tbRankingBoard.getColumnModel().getColumn(0).setPreferredWidth(50);   // Rank
        tbRankingBoard.getColumnModel().getColumn(1).setPreferredWidth(200);  // Name
        tbRankingBoard.getColumnModel().getColumn(2).setPreferredWidth(150);  // Time
        tbRankingBoard.getColumnModel().getColumn(3).setPreferredWidth(150);  // Score
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbBack = new javax.swing.JLabel();
        lbbackground = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbRankingBoard = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ranking Board");

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setLayout(null);

        lbBack.setBackground(new java.awt.Color(0, 255, 255));
        lbBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbBack.setForeground(new java.awt.Color(255, 0, 0));
        lbBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backIcon.png"))); // NOI18N
        lbBack.setText("BACK");
        lbBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbBack.setOpaque(true);
        lbBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBackMouseClicked(evt);
            }
        });
        jPanel1.add(lbBack);
        lbBack.setBounds(0, 650, 170, 50);

        lbbackground.setBackground(new java.awt.Color(0, 0, 204));
        lbbackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rankingBoard.gif"))); // NOI18N
        lbbackground.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbbackground.setOpaque(true);
        jPanel1.add(lbbackground);
        lbbackground.setBounds(230, 40, 210, 200);

        tbRankingBoard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rank", "Name", "Time", "Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbRankingBoard.setOpaque(false);
        tbRankingBoard.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbRankingBoardAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(tbRankingBoard);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(20, 280, 648, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBackMouseClicked
        // TODO add your handling code here:
        StartMenu_Frame startMenu = new StartMenu_Frame();
        startMenu.setVisible(true); // Mở lại menu chính
        this.dispose(); // Đóng cửa sổ game hiện tại
    }//GEN-LAST:event_lbBackMouseClicked

    private void tbRankingBoardAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbRankingBoardAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbRankingBoardAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RankingBoard_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RankingBoard_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RankingBoard_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RankingBoard_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RankingBoard_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbBack;
    private javax.swing.JLabel lbbackground;
    private javax.swing.JTable tbRankingBoard;
    // End of variables declaration//GEN-END:variables
}
