/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacman_demo_v2;

import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author luuhu
 */
public class RankingBoard_Frame extends javax.swing.JFrame {

    private ScoreManager scoreManager;

    /**
     * Creates new form StartMenu_Frame
     */
    public RankingBoard_Frame() {
        initComponents();
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"));
        this.setIconImage(icon.getImage());
        this.setSize(698, 739);          // Đặt kích thước
        this.setResizable(false);        // Không cho phép thay đổi kích thước
        this.setLocationRelativeTo(null); // Đặt cửa sổ ra giữa màn hình

        scoreManager = new ScoreManager();

        loadAndDisplayScores();

    }

    private void styleLabel(JLabel label) {
        label.setFont(new Font("Tahoma", Font.BOLD, 16)); // Đặt font chữ
        label.setForeground(Color.WHITE); // Đặt màu chữ
    }

    // THÊM MỚI: Phương thức tải và hiển thị điểm
    private void loadAndDisplayScores() {
        // Đọc danh sách điểm đã được sắp xếp
        List<PlayerScore> topScores = scoreManager.readScores();

        // Nhóm các label lại để dễ xử lý
        JLabel[] nameLabels = {lbText1st1, lbText2nd1, lbText3rd1, lbText4th1, lbText5th1};
        JLabel[] timeLabels = {lbText1st2, lbText2nd2, lbText3rd2, lbText4th2, lbText5th2};
        JLabel[] scoreLabels = {lbText1st3, lbText2nd3, lbText3rd3, lbText4th3, lbText5th3};

        // Áp dụng style cho tất cả các label
        for (int i = 0; i < 5; i++) {
            styleLabel(nameLabels[i]);
            styleLabel(timeLabels[i]);
            styleLabel(scoreLabels[i]);
        }

        // Hiển thị thông tin top 3 người chơi
        for (int i = 0; i < 5; i++) {
            if (i < topScores.size()) {
                // Nếu có đủ người chơi trong danh sách
                PlayerScore ps = topScores.get(i);
                nameLabels[i].setText(ps.getUsername());      // Name
                timeLabels[i].setText(ps.getTime());          // Time
                scoreLabels[i].setText(String.valueOf(ps.getScore())); // Score
            } else {
                // Nếu không đủ 3 người, hiển thị ký tự trống
                nameLabels[i].setText("---");
                timeLabels[i].setText("--:--:--");
                scoreLabels[i].setText("---");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbback = new javax.swing.JLabel();
        lbText3rd3 = new javax.swing.JLabel();
        lbText3rd2 = new javax.swing.JLabel();
        lbText3rd1 = new javax.swing.JLabel();
        lbText2nd3 = new javax.swing.JLabel();
        lbText2nd2 = new javax.swing.JLabel();
        lbText2nd1 = new javax.swing.JLabel();
        lbText1st3 = new javax.swing.JLabel();
        lbText1st2 = new javax.swing.JLabel();
        lbText1st1 = new javax.swing.JLabel();
        lbText5th3 = new javax.swing.JLabel();
        lbText5th2 = new javax.swing.JLabel();
        lbText5th1 = new javax.swing.JLabel();
        lbText4th3 = new javax.swing.JLabel();
        lbText4th2 = new javax.swing.JLabel();
        lbText4th1 = new javax.swing.JLabel();
        lbBgRankingBoard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ranking Board");

        jPanel1.setBackground(new java.awt.Color(255, 102, 255));
        jPanel1.setLayout(null);

        lbback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home.png"))); // NOI18N
        lbback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbback.setPreferredSize(new java.awt.Dimension(117, 54));
        lbback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbbackMouseClicked(evt);
            }
        });
        jPanel1.add(lbback);
        lbback.setBounds(20, 630, 120, 50);

        lbText3rd3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lbText3rd3);
        lbText3rd3.setBounds(490, 307, 70, 40);

        lbText3rd2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbText3rd2);
        lbText3rd2.setBounds(330, 307, 100, 40);

        lbText3rd1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lbText3rd1);
        lbText3rd1.setBounds(200, 307, 120, 40);

        lbText2nd3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lbText2nd3);
        lbText2nd3.setBounds(490, 242, 70, 40);

        lbText2nd2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbText2nd2);
        lbText2nd2.setBounds(330, 242, 100, 40);

        lbText2nd1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lbText2nd1);
        lbText2nd1.setBounds(200, 242, 120, 40);

        lbText1st3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lbText1st3);
        lbText1st3.setBounds(490, 179, 70, 40);

        lbText1st2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbText1st2);
        lbText1st2.setBounds(330, 179, 100, 40);

        lbText1st1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lbText1st1);
        lbText1st1.setBounds(200, 179, 120, 40);

        lbText5th3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lbText5th3);
        lbText5th3.setBounds(490, 436, 70, 40);

        lbText5th2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbText5th2);
        lbText5th2.setBounds(330, 436, 100, 40);

        lbText5th1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lbText5th1);
        lbText5th1.setBounds(200, 436, 120, 40);

        lbText4th3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lbText4th3);
        lbText4th3.setBounds(490, 372, 70, 40);

        lbText4th2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbText4th2);
        lbText4th2.setBounds(330, 372, 100, 40);

        lbText4th1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lbText4th1);
        lbText4th1.setBounds(200, 372, 120, 40);

        lbBgRankingBoard.setBackground(new java.awt.Color(51, 153, 255));
        lbBgRankingBoard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBgRankingBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rankingBoardBG.png"))); // NOI18N
        lbBgRankingBoard.setOpaque(true);
        jPanel1.add(lbBgRankingBoard);
        lbBgRankingBoard.setBounds(0, 0, 700, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbackMouseClicked
        // TODO add your handling code here:
        StartMenu_Frame startMenu = new StartMenu_Frame();
        startMenu.setVisible(true); // Mở lại menu chính
        this.dispose(); // Đóng cửa sổ game hiện tại
    }//GEN-LAST:event_lbbackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RankingBoard_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RankingBoard_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RankingBoard_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RankingBoard_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RankingBoard_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBgRankingBoard;
    private javax.swing.JLabel lbText1st1;
    private javax.swing.JLabel lbText1st2;
    private javax.swing.JLabel lbText1st3;
    private javax.swing.JLabel lbText2nd1;
    private javax.swing.JLabel lbText2nd2;
    private javax.swing.JLabel lbText2nd3;
    private javax.swing.JLabel lbText3rd1;
    private javax.swing.JLabel lbText3rd2;
    private javax.swing.JLabel lbText3rd3;
    private javax.swing.JLabel lbText4th1;
    private javax.swing.JLabel lbText4th2;
    private javax.swing.JLabel lbText4th3;
    private javax.swing.JLabel lbText5th1;
    private javax.swing.JLabel lbText5th2;
    private javax.swing.JLabel lbText5th3;
    private javax.swing.JLabel lbback;
    // End of variables declaration//GEN-END:variables
}
