/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacman_demo_v2;

import java.io.File;
import java.net.URL;
import javafx.embed.swing.JFXPanel;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;

/**
 *
 * @author luuhu
 */
public class StartMenu_Frame extends javax.swing.JFrame {

    /**
     * Creates new form StartMenu_Frame
     */
    static {
        new JFXPanel();
    } // khởi tạo JavaFX runtime

    public StartMenu_Frame() {
        initComponents();

        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"));
        this.setIconImage(icon.getImage());
        this.setSize(694, 725);
        this.setResizable(false);
        this.setLocationRelativeTo(null);

        // phát nhạc nền (background thread)
        new Thread(() -> {
            try {
                String[] paths = {"/msc/ms.mp3", "src/msc/ms.mp3", "msc/ms.mp3"};
                URL url = null;
                for (String p : paths) {
                    url = StartMenu_Frame.class.getResource(p);
                    if (url == null) {
                        File f = new File(p);
                        if (f.exists()) {
                            url = f.toURI().toURL();
                        }
                    }
                    if (url != null) {
                        break;
                    }
                }
                if (url != null) {
                    MediaPlayer player = new MediaPlayer(new Media(url.toExternalForm()));
                    player.setCycleCount(MediaPlayer.INDEFINITE); // loop nhạc
                    player.play();
                }
            } catch (Exception e) {
                /* bỏ qua lỗi */ }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        lbPlay = new javax.swing.JLabel();
        lbTutorial = new javax.swing.JLabel();
        lbRankingBoard = new javax.swing.JLabel();
        lbAboutUs = new javax.swing.JLabel();
        lbExit = new javax.swing.JLabel();
        lbbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");

        jPanel1.setLayout(null);

        lbLogo.setBackground(new java.awt.Color(204, 255, 0));
        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pacManLogo.png"))); // NOI18N
        lbLogo.setOpaque(true);
        jPanel1.add(lbLogo);
        lbLogo.setBounds(270, 120, 190, 190);

        lbPlay.setBackground(new java.awt.Color(0, 255, 255));
        lbPlay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbPlay.setForeground(new java.awt.Color(204, 204, 0));
        lbPlay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/playIcon.png"))); // NOI18N
        lbPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPlayMouseClicked(evt);
            }
        });
        jPanel1.add(lbPlay);
        lbPlay.setBounds(100, 380, 540, 50);

        lbTutorial.setBackground(new java.awt.Color(0, 255, 255));
        lbTutorial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTutorial.setForeground(new java.awt.Color(153, 0, 153));
        lbTutorial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTutorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tutorialIcon.png"))); // NOI18N
        lbTutorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbTutorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbTutorialMouseClicked(evt);
            }
        });
        jPanel1.add(lbTutorial);
        lbTutorial.setBounds(100, 440, 540, 50);

        lbRankingBoard.setBackground(new java.awt.Color(0, 255, 255));
        lbRankingBoard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbRankingBoard.setForeground(new java.awt.Color(0, 0, 153));
        lbRankingBoard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRankingBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rankingBoardIcon.png"))); // NOI18N
        lbRankingBoard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbRankingBoard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbRankingBoardMouseClicked(evt);
            }
        });
        jPanel1.add(lbRankingBoard);
        lbRankingBoard.setBounds(100, 500, 540, 50);

        lbAboutUs.setBackground(new java.awt.Color(0, 255, 255));
        lbAboutUs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAboutUs.setForeground(new java.awt.Color(0, 153, 0));
        lbAboutUs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aboutUsIcon.png"))); // NOI18N
        lbAboutUs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAboutUsMouseClicked(evt);
            }
        });
        jPanel1.add(lbAboutUs);
        lbAboutUs.setBounds(100, 560, 540, 50);

        lbExit.setBackground(new java.awt.Color(0, 255, 255));
        lbExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbExit.setForeground(new java.awt.Color(255, 0, 0));
        lbExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exitIcon.png"))); // NOI18N
        lbExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExitMouseClicked(evt);
            }
        });
        jPanel1.add(lbExit);
        lbExit.setBounds(100, 620, 540, 50);

        lbbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PacManloop.gif"))); // NOI18N
        lbbackground.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lbbackground);
        lbbackground.setBounds(0, 10, 726, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPlayMouseClicked
        // TODO add your handling code here:
        ChoiceCharacter_Frame pacManGame = new ChoiceCharacter_Frame();
        pacManGame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lbPlayMouseClicked

    private void lbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseClicked
        // TODO add your handling code here:
        thankYou_Frame tyf = new thankYou_Frame();
        tyf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lbExitMouseClicked

    private void lbRankingBoardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRankingBoardMouseClicked
        // TODO add your handling code here:
        RankingBoard_Frame rkf = new RankingBoard_Frame();
        rkf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbRankingBoardMouseClicked

    private void lbTutorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTutorialMouseClicked
        // TODO add your handling code here:
        Tutorial_Frame1 tut = new Tutorial_Frame1();
        tut.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbTutorialMouseClicked

    private void lbAboutUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAboutUsMouseClicked
        // TODO add your handling code here:
        AboutUs_Frame tut = new AboutUs_Frame();
        tut.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbAboutUsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartMenu_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartMenu_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartMenu_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartMenu_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartMenu_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAboutUs;
    private javax.swing.JLabel lbExit;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbPlay;
    private javax.swing.JLabel lbRankingBoard;
    private javax.swing.JLabel lbTutorial;
    private javax.swing.JLabel lbbackground;
    // End of variables declaration//GEN-END:variables
}
