/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pacman_demo_v2;

/**
 *
 * @author luuhu
 */
public class Tutorial_Frame2 extends javax.swing.JFrame {

    /**
     * Creates new form StartMenu_Frame
     */
    public Tutorial_Frame2() {
        initComponents();
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"));
        this.setIconImage(icon.getImage());
        this.setSize(625, 670);          // Đặt kích thước
        this.setResizable(false);        // Không cho phép thay đổi kích thước
        this.setLocationRelativeTo(null); // Đặt cửa sổ ra giữa màn hình
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbnext1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbback = new javax.swing.JLabel();
        lbnext = new javax.swing.JLabel();
        lbnext2 = new javax.swing.JLabel();
        lbbackground = new javax.swing.JLabel();

        lbnext1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home.png"))); // NOI18N
        lbnext1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbnext1.setPreferredSize(new java.awt.Dimension(120, 54));
        lbnext1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbnext1MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tutotrial");

        jPanel1.setLayout(null);

        lbback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tutback.png"))); // NOI18N
        lbback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbback.setPreferredSize(new java.awt.Dimension(117, 54));
        lbback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbbackMouseClicked(evt);
            }
        });
        jPanel1.add(lbback);
        lbback.setBounds(30, 560, 120, 50);

        lbnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tutnext.png"))); // NOI18N
        lbnext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbnext.setPreferredSize(new java.awt.Dimension(120, 54));
        lbnext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbnextMouseClicked(evt);
            }
        });
        jPanel1.add(lbnext);
        lbnext.setBounds(160, 560, 130, 50);

        lbnext2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home.png"))); // NOI18N
        lbnext2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbnext2.setPreferredSize(new java.awt.Dimension(120, 54));
        lbnext2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbnext2MouseClicked(evt);
            }
        });
        jPanel1.add(lbnext2);
        lbnext2.setBounds(460, 560, 130, 50);

        lbbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tutorial/Tut2.png"))); // NOI18N
        lbbackground.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lbbackground);
        lbbackground.setBounds(0, 10, 620, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbackMouseClicked
        // TODO add your handling code here:
        Tutorial_Frame1 tut = new Tutorial_Frame1();
        tut.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbbackMouseClicked

    private void lbnextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbnextMouseClicked
        // TODO add your handling code here:
        Tutorial_Frame3 tut = new Tutorial_Frame3();
        tut.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbnextMouseClicked

    private void lbnext1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbnext1MouseClicked
        // TODO add your handling code here:
        StartMenu_Frame startMenu = new StartMenu_Frame();
        startMenu.setVisible(true); // Mở lại menu chính
        this.dispose(); // Đóng cửa sổ game hiện tại
    }//GEN-LAST:event_lbnext1MouseClicked

    private void lbnext2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbnext2MouseClicked
        // TODO add your handling code here:
        StartMenu_Frame startMenu = new StartMenu_Frame();
        startMenu.setVisible(true); // Mở lại menu chính
        this.dispose(); // Đóng cửa sổ game hiện tại
    }//GEN-LAST:event_lbnext2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tutorial_Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tutorial_Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tutorial_Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tutorial_Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tutorial_Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbback;
    private javax.swing.JLabel lbbackground;
    private javax.swing.JLabel lbnext;
    private javax.swing.JLabel lbnext1;
    private javax.swing.JLabel lbnext2;
    // End of variables declaration//GEN-END:variables
}
